"""initial schema

Revision ID: 7f0736d5b557
Revises: 
Create Date: 2026-09-08 06:13:34.229130
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f0736d5b557'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('father_or_spouse_name', sa.String(length=255), nullable=True),
    sa.Column('id_type', sa.String(length=24), nullable=True),
    sa.Column('id_number', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_owners_data_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('states',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('centroid_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('centroid_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('workflow_stage_definitions',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('expected_duration_days', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('sequence_order')
    )
    op.create_table('districts',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_districts_state_code'), 'districts', ['state_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('district_code', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('related_type', sa.String(length=40), nullable=True),
    sa.Column('related_id', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('requiring_body', sa.String(length=255), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('district_code', sa.String(length=8), nullable=True),
    sa.Column('estimated_area_ha', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('estimated_compensation_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_projects_data_source'),
    sa.CheckConstraint("status IN ('PLANNED','ACTIVE','DELAYED','ON_HOLD','COMPLETED')", name='ck_projects_status'),
    sa.CheckConstraint('estimated_area_ha >= 0', name='ck_projects_area_nonneg'),
    sa.CheckConstraint('estimated_compensation_inr >= 0', name='ck_projects_comp_nonneg'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_stage'], ['workflow_stage_definitions.code'], ),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_projects_state_code'), 'projects', ['state_code'], unique=False)
    op.create_geospatial_table('land_parcels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ulpin', sa.String(length=14), nullable=False),
    sa.Column('khasra_number', sa.String(length=64), nullable=False),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('tehsil', sa.String(length=128), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('district_code', sa.String(length=8), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('acquisition_status', sa.String(length=24), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=True),
    sa.Column('centroid', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geometry_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("acquisition_status IN ('NOT_STARTED','IN_PROCESS','ACQUIRED','DISPUTED','DROPPED')", name='ck_parcels_acq_status'),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_parcels_data_source'),
    sa.CheckConstraint('area_ha > 0', name='ck_parcels_area_positive'),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['state_code'], ['states.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ulpin')
    )
    op.create_geospatial_index('idx_land_parcels_centroid', 'land_parcels', ['centroid'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_land_parcels_geom', 'land_parcels', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_land_parcels_khasra_number', 'land_parcels', ['khasra_number'], unique=False)
    op.create_index(op.f('ix_land_parcels_project_id'), 'land_parcels', ['project_id'], unique=False)
    op.create_index('ix_land_parcels_state_district', 'land_parcels', ['state_code', 'district_code'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_number', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('required_area_ha', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('estimated_compensation_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('affected_families_count', sa.Integer(), nullable=True),
    sa.Column('proposed_start', sa.Date(), nullable=True),
    sa.Column('proposed_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_remarks', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_proposals_data_source'),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','UNDER_VERIFICATION','APPROVED','REJECTED')", name='ck_proposals_status'),
    sa.CheckConstraint('affected_families_count >= 0', name='ck_proposals_families_nonneg'),
    sa.CheckConstraint('required_area_ha >= 0', name='ck_proposals_area_nonneg'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_number')
    )
    op.create_index(op.f('ix_proposals_project_id'), 'proposals', ['project_id'], unique=False)
    op.create_table('acquisition_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('current_stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('notified_area_ha', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('acquired_area_ha', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_stage_exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_cases_data_source'),
    sa.CheckConstraint("status IN ('OPEN','ON_HOLD','CLOSED','DROPPED')", name='ck_cases_status'),
    sa.ForeignKeyConstraint(['current_stage'], ['workflow_stage_definitions.code'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number'),
    sa.UniqueConstraint('project_id', 'parcel_id', name='uq_acquisition_cases_project_parcel')
    )
    op.create_index(op.f('ix_acquisition_cases_current_stage'), 'acquisition_cases', ['current_stage'], unique=False)
    op.create_index('ix_acquisition_cases_parcel_id', 'acquisition_cases', ['parcel_id'], unique=False)
    op.create_index('ix_acquisition_cases_project_stage_status', 'acquisition_cases', ['project_id', 'current_stage', 'status'], unique=False)
    op.create_table('affected_families',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=True),
    sa.Column('family_head_name', sa.String(length=255), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('is_displaced', sa.Boolean(), nullable=False),
    sa.Column('contact', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_families_data_source'),
    sa.CheckConstraint("status IN ('IDENTIFIED','ASSISTED','RESETTLED','CLOSED')", name='ck_families_status'),
    sa.CheckConstraint('member_count > 0', name='ck_families_member_count'),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affected_families_project_id'), 'affected_families', ['project_id'], unique=False)
    op.create_table('parcel_owners',
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('ownership_share_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ownership_type', sa.String(length=24), nullable=False),
    sa.CheckConstraint("ownership_type IN ('SOLE','JOINT','LEGAL_HEIR','ENCUMBERED')", name='ck_parcel_owners_type'),
    sa.CheckConstraint('ownership_share_pct >= 0 AND ownership_share_pct <= 100', name='ck_parcel_owners_share'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parcel_id', 'owner_id')
    )
    op.create_table('proposal_parcels',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposal_id', 'parcel_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=40), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('parcel_id', sa.Uuid(), nullable=True),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_alerts_data_source'),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_alerts_severity'),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_recipient_user_id'), 'alerts', ['recipient_user_id'], unique=False)
    op.create_table('compensation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=False),
    sa.Column('assessed_amount_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('paid_amount_inr', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_compensation_data_source'),
    sa.CheckConstraint("status IN ('NOT_ASSESSED','ASSESSED','PARTIAL','PAID','DISPUTED')", name='ck_compensation_status'),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acquisition_case_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('parcel_id', sa.Uuid(), nullable=True),
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_documents_data_source'),
    sa.CheckConstraint("doc_type IN ('LAND_RECORD','SIA_REPORT','OWNERSHIP_PROOF','COMPENSATION','AWARD','RR','PHOTO','OTHER')", name='ck_documents_type'),
    sa.CheckConstraint("verification_status IN ('PENDING','VERIFIED','REJECTED')", name='ck_documents_verification'),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_parcel_id'), 'documents', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('field_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parcel_id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_verified', sa.Boolean(), nullable=True),
    sa.Column('land_info_verified', sa.Boolean(), nullable=True),
    sa.Column('documents_verified', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_field_data_source'),
    sa.CheckConstraint("status IN ('ASSIGNED','IN_PROGRESS','SUBMITTED','ACCEPTED','REJECTED')", name='ck_field_status'),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_verifications_assigned_to'), 'field_verifications', ['assigned_to'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('trained_on', sa.String(length=16), server_default='SYNTHETIC', nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('predicted_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("risk_level IN ('LOW','MEDIUM','HIGH')", name='ck_ml_risk_level'),
    sa.CheckConstraint("trained_on IN ('SYNTHETIC','AUTHORIZED_HISTORICAL')", name='ck_ml_trained_on'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 1', name='ck_ml_risk_score'),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], ),
    sa.ForeignKeyConstraint(['predicted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_acquisition_case_id'), 'ml_predictions', ['acquisition_case_id'], unique=False)
    op.create_table('possession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('area_ha', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taken_by', sa.Uuid(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_possession_data_source'),
    sa.CheckConstraint("status IN ('NOT_TAKEN','PARTIAL','TAKEN')", name='ck_possession_status'),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], ),
    sa.ForeignKeyConstraint(['taken_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acquisition_case_id')
    )
    op.create_table('rehabilitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('package_type', sa.String(length=64), nullable=True),
    sa.Column('amount_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_rehab_data_source'),
    sa.CheckConstraint("status IN ('NOT_STARTED','IN_PROGRESS','COMPLETED')", name='ck_rehab_status'),
    sa.ForeignKeyConstraint(['family_id'], ['affected_families.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id')
    )
    op.create_table('resettlement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_name', sa.String(length=128), nullable=True),
    sa.Column('plot_allotted', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('allotted_date', sa.Date(), nullable=True),
    sa.Column('possession_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.String(length=20), server_default='SYNTHETIC', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_source IN ('SYNTHETIC','MOCK_ADAPTER','EXTERNAL')", name='ck_resettlement_data_source'),
    sa.CheckConstraint("status IN ('NOT_ALLOTTED','ALLOTTED','POSSESSED')", name='ck_resettlement_status'),
    sa.ForeignKeyConstraint(['family_id'], ['affected_families.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id')
    )
    op.create_table('workflow_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('acquisition_case_id', sa.Uuid(), nullable=False),
    sa.Column('from_stage', sa.String(length=40), nullable=True),
    sa.Column('to_stage', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_case_id'], ['acquisition_cases.id'], ),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='fk_workflow_events_document_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_events_acquisition_case_id'), 'workflow_events', ['acquisition_case_id'], unique=False)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_workflow_event_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'workflow_events is append-only';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER workflow_events_no_update_delete
        BEFORE UPDATE OR DELETE ON workflow_events
        FOR EACH ROW
        EXECUTE FUNCTION prevent_workflow_event_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS workflow_events_no_update_delete ON workflow_events")
    op.execute("DROP FUNCTION IF EXISTS prevent_workflow_event_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_acquisition_case_id'), table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_table('resettlement')
    op.drop_table('rehabilitation')
    op.drop_table('possession')
    op.drop_index(op.f('ix_ml_predictions_acquisition_case_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_field_verifications_assigned_to'), table_name='field_verifications')
    op.drop_table('field_verifications')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_parcel_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('compensation')
    op.drop_index(op.f('ix_alerts_recipient_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('proposal_parcels')
    op.drop_table('parcel_owners')
    op.drop_index(op.f('ix_affected_families_project_id'), table_name='affected_families')
    op.drop_table('affected_families')
    op.drop_index('ix_acquisition_cases_project_stage_status', table_name='acquisition_cases')
    op.drop_index('ix_acquisition_cases_parcel_id', table_name='acquisition_cases')
    op.drop_index(op.f('ix_acquisition_cases_current_stage'), table_name='acquisition_cases')
    op.drop_table('acquisition_cases')
    op.drop_index(op.f('ix_proposals_project_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_land_parcels_state_district', table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_project_id'), table_name='land_parcels')
    op.drop_index('ix_land_parcels_khasra_number', table_name='land_parcels')
    op.drop_geospatial_index('idx_land_parcels_geom', table_name='land_parcels', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_index('idx_land_parcels_centroid', table_name='land_parcels', postgresql_using='gist', column_name='centroid')
    op.drop_geospatial_table('land_parcels')
    op.drop_index(op.f('ix_projects_state_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_districts_state_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('workflow_stage_definitions')
    op.drop_table('states')
    op.drop_table('roles')
    op.drop_table('owners')
    # ### end Alembic commands ###
